# Generated by Django 4.2.4 on 2023-08-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
