# Generated by Django 4.2.4 on 2023-08-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_name_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='a_date'),
        ),
    ]
